import type {
  Agent,
  Message,
  DebateContext,
  DebateRound,
  TmuxSession,
  TmuxPane,
  MementoContext,
  ApprovalItem,
  SystemStatus,
  DelegationChip,
} from './types'

// 17 Agents with Korean/English labels
export const agents: Agent[] = [
  // Core Agents
  {
    id: 'chae-arin',
    name: '채아린',
    nameEn: 'Chae Arin',
    role: 'Orchestrator',
    roleKo: '지휘자',
    model: 'codex-session',
    avatar: 'OR',
    avatarColor: 'orchestrator',
    isPrimary: true,
    canDelegate: true,
    category: 'core',
    status: 'active',
    description: 'Primary orchestrator. Manages all agent coordination and delegation.',
  },
  {
    id: 'architect',
    name: 'Architect',
    nameEn: 'Architect',
    role: 'Architect',
    roleKo: '설계자',
    model: 'gpt-5.5-pro',
    avatar: 'AR',
    avatarColor: 'architect',
    isPrimary: false,
    canDelegate: false,
    category: 'core',
    status: 'ready',
    description: 'Protocol, Event Storage, type boundaries.',
  },
  {
    id: 'reviewer',
    name: 'Reviewer',
    nameEn: 'Reviewer',
    role: 'Reviewer',
    roleKo: '리스크',
    model: 'claude-opus-4-6',
    avatar: 'RE',
    avatarColor: 'reviewer',
    isPrimary: false,
    canDelegate: false,
    category: 'core',
    status: 'idle',
    description: 'Risk analysis, mutual critique, security review.',
  },
  {
    id: 'builder',
    name: 'Builder',
    nameEn: 'Builder',
    role: 'Builder',
    roleKo: '구현자',
    model: 'claude-opus-4-6',
    avatar: 'BU',
    avatarColor: 'builder',
    isPrimary: false,
    canDelegate: false,
    category: 'core',
    status: 'idle',
    description: 'Core logic implementation, coding packet execution.',
  },
  // Specialist Agents
  {
    id: 'code-expert',
    name: 'Code Expert',
    nameEn: 'Code Expert',
    role: 'Code Expert',
    roleKo: '핵심 로직',
    model: 'codex-session',
    avatar: 'CE',
    avatarColor: 'expert',
    isPrimary: false,
    canDelegate: false,
    category: 'specialist',
    status: 'idle',
    description: 'Core logic, refactoring, complex implementation.',
  },
  {
    id: 'frontend-dev',
    name: 'Frontend Dev',
    nameEn: 'Frontend Dev',
    role: 'Frontend Dev',
    roleKo: 'desktop UI',
    model: 'gpt-5.5-pro',
    avatar: 'FE',
    avatarColor: 'builder',
    isPrimary: false,
    canDelegate: false,
    category: 'specialist',
    status: 'active',
    description: 'Desktop UI, Workbench, Execution Slot.',
  },
  {
    id: 'backend-dev',
    name: 'Backend Dev',
    nameEn: 'Backend Dev',
    role: 'Backend Dev',
    roleKo: 'server/sync',
    model: 'claude-opus-4-6',
    avatar: 'BE',
    avatarColor: 'builder',
    isPrimary: false,
    canDelegate: false,
    category: 'specialist',
    status: 'idle',
    description: 'Server, sync, DGX connection support.',
  },
  {
    id: 'qa-security',
    name: 'QA & Security',
    nameEn: 'QA & Security',
    role: 'QA & Security',
    roleKo: '테스트/redaction',
    model: 'gpt-5.5-pro',
    avatar: 'QA',
    avatarColor: 'reviewer',
    isPrimary: false,
    canDelegate: false,
    category: 'specialist',
    status: 'online',
    description: 'Testing, security audit, redaction verification.',
  },
  // Companion Agents (9-17)
  {
    id: 'maomao',
    name: 'Maomao',
    nameEn: 'Maomao',
    role: 'Companion',
    roleKo: '동반자',
    model: 'gpt-5.5-pro',
    avatar: 'MM',
    avatarColor: 'companion',
    isPrimary: false,
    canDelegate: true,
    category: 'companion',
    status: 'online',
    description: 'Analytical companion. Medical/logical reasoning.',
  },
  {
    id: 'sparkle',
    name: 'Sparkle',
    nameEn: 'Sparkle',
    role: 'Companion',
    roleKo: '동반자',
    model: 'claude-opus-4-6',
    avatar: 'SP',
    avatarColor: 'companion',
    isPrimary: false,
    canDelegate: true,
    category: 'companion',
    status: 'idle',
    description: 'Strategic thinker. Long-term planning.',
  },
  {
    id: 'yui',
    name: 'Yui',
    nameEn: 'Yui',
    role: 'Companion',
    roleKo: '동반자',
    model: 'gpt-5.5-pro',
    avatar: 'YU',
    avatarColor: 'companion',
    isPrimary: false,
    canDelegate: true,
    category: 'companion',
    status: 'offline',
    description: 'Empathetic companion. User experience focus.',
  },
  {
    id: 'robin',
    name: 'Robin',
    nameEn: 'Robin',
    role: 'Companion',
    roleKo: '동반자',
    model: 'gpt-5.5-pro',
    avatar: 'RO',
    avatarColor: 'companion',
    isPrimary: false,
    canDelegate: true,
    category: 'companion',
    status: 'idle',
    description: 'Information specialist. Research and synthesis.',
  },
  {
    id: 'kafka',
    name: 'Kafka',
    nameEn: 'Kafka',
    role: 'Companion',
    roleKo: '동반자',
    model: 'claude-opus-4-6',
    avatar: 'KF',
    avatarColor: 'companion',
    isPrimary: false,
    canDelegate: true,
    category: 'companion',
    status: 'offline',
    description: 'Creative disruptor. Unconventional solutions.',
  },
  {
    id: 'herta',
    name: 'Herta',
    nameEn: 'Herta',
    role: 'Companion',
    roleKo: '동반자',
    model: 'gpt-5.5-pro',
    avatar: 'HT',
    avatarColor: 'companion',
    isPrimary: false,
    canDelegate: true,
    category: 'companion',
    status: 'idle',
    description: 'Scientific genius. Complex problem analysis.',
  },
  {
    id: 'acheron',
    name: 'Acheron',
    nameEn: 'Acheron',
    role: 'Companion',
    roleKo: '동반자',
    model: 'claude-opus-4-6',
    avatar: 'AC',
    avatarColor: 'companion',
    isPrimary: false,
    canDelegate: true,
    category: 'companion',
    status: 'offline',
    description: 'Silent observer. Deep pattern recognition.',
  },
  {
    id: 'black-swan',
    name: 'Black Swan',
    nameEn: 'Black Swan',
    role: 'Companion',
    roleKo: '동반자',
    model: 'gpt-5.5-pro',
    avatar: 'BS',
    avatarColor: 'companion',
    isPrimary: false,
    canDelegate: true,
    category: 'companion',
    status: 'idle',
    description: 'Dream interpreter. Subconscious analysis.',
  },
  {
    id: 'fu-xuan',
    name: 'Fu Xuan',
    nameEn: 'Fu Xuan',
    role: 'Companion',
    roleKo: '동반자',
    model: 'gpt-5.5-pro',
    avatar: 'FX',
    avatarColor: 'companion',
    isPrimary: false,
    canDelegate: true,
    category: 'companion',
    status: 'online',
    description: 'Divination master. Probability assessment.',
  },
]

export const getAgentById = (id: string): Agent | undefined => 
  agents.find(a => a.id === id)

export const getPrimaryAgent = (): Agent => 
  agents.find(a => a.isPrimary) || agents[0]

export const getAgentsByCategory = (category: Agent['category']): Agent[] =>
  agents.filter(a => a.category === category)

// Sample Messages
export const sampleMessages: Message[] = [
  {
    id: 'msg-1',
    agentId: 'user',
    content: '문서에 맞춰 첫 구현 골격을 만들자. 토론으로 확대할 수 있게 경계도 살려줘.',
    timestamp: new Date('2024-01-15T10:30:00'),
    type: 'user',
  },
  {
    id: 'msg-2',
    agentId: 'chae-arin',
    content: 'protocol, provider stub, agent runtime stub, desktop board를 먼저 연결하고 실제 모델 호출은 막아둔다.',
    timestamp: new Date('2024-01-15T10:30:30'),
    type: 'agent',
  },
  {
    id: 'msg-3',
    agentId: 'system',
    content: 'Debate session initiated. 7 rounds planned.',
    timestamp: new Date('2024-01-15T10:31:00'),
    type: 'system',
  },
]

// Delegation Chips (only for 채아린/companion)
export const delegationChips: DelegationChip[] = [
  { action: '토론 전환', enabled: true, shortcut: '⇧D' },
  { action: '패킷 생성', enabled: true, shortcut: '⇧P' },
  { action: '실행 슬롯', enabled: true, shortcut: '⇧E' },
  { action: '백업 상태', enabled: true, shortcut: '⇧B' },
  { action: 'Telegram', enabled: false, shortcut: '⇧T' },
]

// Debate Context Mock
export const sampleDebateContext: DebateContext = {
  id: 'debate-1',
  topic: '문서에 맞춰 첫 구현 골격을 만들자. 토론으로 확대할 수 있게 경계도 살려줘.',
  userRequest: 'user: 문서에 맞춰 첫 구현 골격을 만들자. 토론으로 확대할 수 있게 경계도 살려줘. / assistant: protocol, provider stub, agent runtime stub, desktop board를 먼저 연결하고 실제 모델 호출은 막아둔다.',
  stages: ['문제 정의', '1차 제안', '상호 비판', '오케스트레이터 요약', '보안 라운드', '최종 결정', '코딩 패킷'],
  currentStage: '최종 결정',
  rounds: [],
}

export const sampleDebateRounds: DebateRound[] = [
  {
    id: 'round-1',
    agentId: 'chae-arin',
    stage: '문제 정의',
    tags: ['합의', '근거'],
    utterance: '현재 대화의 핵심 문제는 "문서에 맞춰 첫 구현 골격을 만들자. 토론으로 확대할 수 있게 경계도 살려줘."이고, 걸 요약어 이니라 걸정적으로 봐거야 할다.',
    timestamp: new Date('2024-01-15T10:32:00'),
  },
  {
    id: 'round-2',
    agentId: 'reviewer',
    stage: '1차 제안',
    tags: ['코딩 영향'],
    utterance: '실행은 아직 mock으로 두되, 이후 CLI slot과 DGX remote slot에 연결할 수 있도록 payload 경계를 고정해야 한다.',
    timestamp: new Date('2024-01-15T10:33:00'),
  },
  {
    id: 'round-3',
    agentId: 'chae-arin',
    stage: '오케스트레이터 요약',
    tags: ['합의', '코딩 영향'],
    utterance: '합의: user: 문서에 맞춰 첫 구현 골격을 만들자. 토론으로 확대할 수 있게 경계도 살려줘. / assistant: protocol, provider stub, agent runtime stub, desktop boa... 다른 행동은 Debate 골격과 Coding Packet 후보로 갱신하는 것이다.',
    timestamp: new Date('2024-01-15T10:35:00'),
  },
  {
    id: 'round-4',
    agentId: 'architect',
    stage: '1차 제안',
    tags: ['근거', '코딩 영향'],
    utterance: 'Conversation context를 Debate Context로 승격하고, 라운드/태그/결과 빌드를 구조화해야 Event Store에 넘기는 편이 좋다.',
    timestamp: new Date('2024-01-15T10:36:00'),
  },
  {
    id: 'round-5',
    agentId: 'reviewer',
    stage: '상호 비판',
    tags: ['반박', '리스크'],
    utterance: '같은 모델에서 여러 가상 에이전트를 만들면 합의가 과장될 수 있다. 검증 모델과 로컬 모델을 모두 선택 가능하게 남겨야 한다.',
    timestamp: new Date('2024-01-15T10:37:00'),
  },
  {
    id: 'round-6',
    agentId: 'architect',
    stage: '보안 라운드',
    tags: ['근거'],
    utterance: 'Status Hub와 Human Peek를 붙이면 숨은 agent-to-agent 흐름과 DGX/local fallback 상태를 한 화면에서 추적할 수 있다.',
    timestamp: new Date('2024-01-15T10:38:00'),
  },
  {
    id: 'round-7',
    agentId: 'chae-arin',
    stage: '최종 결정',
    tags: ['합의', '코딩 영향'],
    utterance: 'Stage3의 첫 결정은 Debate 승격 UI, 라운드 기반 발언, Human Peek, Status Hub를 먼저 연결하는 것이다.',
    timestamp: new Date('2024-01-15T10:40:00'),
  },
]

// Tmux Session Mock
export const sampleTmuxSession: TmuxSession = {
  id: 'session_desktop_001',
  name: 'ai-swarm',
  maxPanes: 10,
  panes: [],
}

export const sampleTmuxPanes: TmuxPane[] = [
  {
    id: 'pane-0',
    paneNumber: 0,
    agentId: 'chae-arin',
    title: 'Discussion & Planning',
    subtitle: 'pane-0',
    status: 'chat active',
    description: '요구사항 / 제품 / 아키텍처 논의',
    currentCommand: "echo 'Discuss requirement first. No direct exec'",
  },
  {
    id: 'pane-1',
    paneNumber: 1,
    agentId: 'chae-arin',
    title: 'Orchestrator Control',
    subtitle: 'pane-1',
    status: 'dispatch gated',
    description: '작업 분배 / 역할 배정 / 지휘',
    currentCommand: "codex 'Break down the current request into rol'",
  },
  {
    id: 'pane-2',
    paneNumber: 2,
    agentId: 'frontend-dev',
    title: 'Status & Monitor',
    subtitle: 'pane-2',
    status: 'watch only',
    description: '진행 로그 / 테스트 / stuck run 감시',
    currentCommand: 'git status --short',
  },
  {
    id: 'pane-3',
    paneNumber: 3,
    agentId: 'builder',
    title: 'Code Expert',
    subtitle: 'pane-3',
    status: 'idle',
    description: '핵심 로직 / 리팩터링 / 복잡 구현',
    currentCommand: "codex 'Inspect the current Coding Packet and |'",
  },
  {
    id: 'pane-4',
    paneNumber: 4,
    agentId: 'architect',
    title: 'Architect',
    subtitle: 'pane-4',
    status: 'ready',
    description: 'protocol / Event Storage / 타입 경계',
    currentCommand: "codex 'Review protocol and event boundaries |'",
  },
  {
    id: 'pane-5',
    paneNumber: 5,
    agentId: 'frontend-dev',
    title: 'Frontend Dev',
    subtitle: 'pane-5',
    status: 'active',
    description: 'desktop UI / Workbench / Execution Slot',
    currentCommand: "codex 'Review the desktop tmux workbench UI'",
  },
  {
    id: 'pane-6',
    paneNumber: 6,
    agentId: 'backend-dev',
    title: 'Backend Dev',
    subtitle: 'pane-6',
    status: 'idle',
    description: 'server / sync / DGX 연결 지원',
  },
  {
    id: 'pane-7',
    paneNumber: 7,
    agentId: 'qa-security',
    title: 'QA & Security',
    subtitle: 'pane-7',
    status: 'guarding',
    description: '테스트 / 권한 / redaction / 회귀검사',
  },
]

// Memento Context Mock
export const sampleMementoContext: MementoContext = {
  activeMemories: 4,
  heldBack: 0,
  relatedLinks: 1,
  stats: [
    { label: 'remember', labelKo: '대화 저장', value: 5, type: 'count' },
    { label: 'recall', labelKo: '4개 후보', value: '4개 후보', type: 'text' },
    { label: 'memory_context', labelKo: '4개 활성', value: '4개 활성', type: 'text' },
    { label: 'reflect', labelKo: '0개 이슈', value: '0개 이슈', type: 'text' },
    { label: 'stats', labelKo: '정상', value: '정상', type: 'text' },
    { label: 'relations', labelKo: '1개 링크', value: '1개 링크', type: 'text' },
    { label: 'activate', labelKo: '3개 활성', value: '3개 활성', type: 'text' },
  ],
  traces: [
    {
      id: 'trace-1',
      title: 'Event Storage first',
      description: '아키텍처 / 프로젝트 / 42%',
      relevance: 42,
      isUsed: true,
    },
    {
      id: 'trace-2',
      title: 'DGX-02 authority server',
      description: '아키텍처 / 프로젝트 / 42%',
      relevance: 42,
      isUsed: true,
    },
    {
      id: 'trace-3',
      title: 'Memento MCP shape',
      description: '아키텍처 / 프로젝트 / 38%',
      relevance: 38,
      isUsed: true,
    },
    {
      id: 'trace-4',
      title: 'Untrusted provider guard',
      description: '현재 작업과 관련 있고 신뢰 정책을 통과함',
      relevance: 35,
      isUsed: true,
    },
  ],
}

// Approval Queue Mock
export const sampleApprovalItems: ApprovalItem[] = [
  { id: 'approval-1', category: '자동', title: 'New WorkItems will be...', description: 'Auto-approved items', priority: 'low', count: 0, hasWaitingItem: false },
  { id: 'approval-2', category: '질문', title: 'DGX-02 Event Sto...', description: 'DGX-02 is authoritative...', priority: 'normal', count: 1, hasWaitingItem: true },
  { id: 'approval-3', category: '질문', title: 'No waiting item', description: 'New WorkItems will be...', priority: 'low', count: 0, hasWaitingItem: false },
  { id: 'approval-4', category: '승인', title: 'No waiting item', description: 'New WorkItems will be...', priority: 'low', count: 0, hasWaitingItem: false },
  { id: 'approval-5', category: '차단', title: 'No waiting item', description: 'New WorkItems will be...', priority: 'low', count: 0, hasWaitingItem: false },
  { id: 'approval-6', category: '대화', title: 'Authority summa...', description: 'DGX-02 owns shared e...', priority: 'high', count: 0, hasWaitingItem: false },
]

// System Status Mock
export const sampleSystemStatus: SystemStatus = {
  dgxMain: 'offline',
  dgxLocal: 'online',
  eventStorage: 'unavailable',
  providers: {
    active: 11,
    total: 13,
  },
  health: 'degraded',
  lastChecked: new Date(),
}
