import type { PatchCandidateInput } from "./patchCandidateSource";

/**
 * Batch 17 LINE A — GENERIC example patch candidates for the PREVIEW seat (clearly
 * fixture, never live) and tests. No domain terms — patch-00x / runner-00x /
 * mission-001 / entity-002 / src/module-*.ts. Static data only: no execution, no
 * import, no network, never applied. Covers pass / warning / blocked safety,
 * claimed / actual / not_run verification, observed true/false, runner/handoff.
 */
export const EXAMPLE_PATCH_CANDIDATES: ReadonlyArray<PatchCandidateInput> = [
  {
    candidateId: "patch-001",
    runnerId: "runner-001",
    missionId: "mission-001",
    createdAt: "2026-06-18T10:00:00.000Z",
    changedFileCount: 2,
    additions: 34,
    deletions: 8,
    safetyStatus: "pass",
    verificationStatus: "actual",
    source: "runner",
    observed: true,
    files: [
      {
        path: "src/module-a.ts",
        change: "modified",
        additions: 20,
        deletions: 6,
        hunkSummary: "tighten input validation",
        risk: "low",
      },
      {
        path: "src/module-a.test.ts",
        change: "added",
        additions: 14,
        deletions: 2,
        hunkSummary: "cover the new guard",
        risk: "low",
      },
    ],
    safetyBlockers: [],
    safetyWarnings: [],
    secretFindingCount: 0,
    pathPolicyStatus: "pass",
    claimedTests: { ran: true, passed: 12, failed: 0 },
    actualTests: { status: "actual", summary: "12 passed observed clean" },
    evidenceRefs: ["ref-ci-001"],
  },
  {
    candidateId: "patch-002",
    runnerId: "runner-001",
    missionId: "mission-001",
    createdAt: "2026-06-18T09:30:00.000Z",
    changedFileCount: 1,
    additions: 180,
    deletions: 4,
    safetyStatus: "warning",
    verificationStatus: "claimed",
    source: "handoff",
    observed: true,
    files: [
      {
        path: "src/module-b.ts",
        change: "modified",
        additions: 180,
        deletions: 4,
        hunkSummary: "large refactor of entity-002 helper",
        risk: "medium",
      },
    ],
    safetyBlockers: [],
    safetyWarnings: ["large change surface", "verification claimed only"],
    secretFindingCount: 0,
    pathPolicyStatus: "pass",
    claimedTests: { ran: true, passed: 5, failed: 0 },
    actualTests: { status: "not_run" },
    evidenceRefs: ["source-001"],
  },
  {
    candidateId: "patch-003",
    runnerId: "runner-002",
    missionId: "mission-001",
    createdAt: "2026-06-18T09:00:00.000Z",
    changedFileCount: 1,
    additions: 9,
    deletions: 0,
    safetyStatus: "blocked",
    verificationStatus: "not_run",
    source: "runner",
    observed: false,
    files: [
      {
        path: "src/util.ts",
        change: "modified",
        additions: 9,
        deletions: 0,
        hunkSummary: "unverified change (not observed)",
        risk: "high",
      },
    ],
    safetyBlockers: ["not_observed", "tests_failed"],
    safetyWarnings: [],
    secretFindingCount: 1,
    pathPolicyStatus: "warning",
    claimedTests: { ran: false, passed: 0, failed: 0 },
    actualTests: { status: "not_run" },
    evidenceRefs: [],
  },
];
