#!/usr/bin/env bash
set -euo pipefail

SESSION_NAME="${AI_SWARM_SESSION:-ai-swarm}"
STATE_DIR="${AI_SWARM_STATE_DIR:-.ai-swarm}"
ENV_FILE="${STATE_DIR}/${SESSION_NAME}.env"
PANE_COUNT="${AI_SWARM_PANE_COUNT:-10}"

roles=(
  discussion
  orchestrator
  status
  code
  architect
  frontend
  backend
  qa
  research
  memory
)

titles=(
  "Discussion & Planning"
  "Orchestrator Control"
  "Status & Monitor"
  "Agent - Code Expert"
  "Agent - Architect"
  "Agent - Frontend Dev"
  "Agent - Backend Dev"
  "Agent - QA & Security"
  "Agent - Research Scout"
  "Agent - Memory Curator"
)

usage() {
  cat <<'USAGE'
Usage:
  scripts/setup-agent-swarm.sh [--reset] [--panes 4-10] [--with-hermes] [--hermes-roles role,role]

Creates the ai-swarm tmux session with 4 to 10 role-based panes.

Options:
  --reset         Kill and recreate an existing ai-swarm session.
  --panes         Number of panes to create. Defaults to 10.
  --with-hermes   After provisioning, start an interactive Hermes Agent
                  worker in each agent pane via
                  scripts/swarm-start-hermes-workers.sh. The desktop
                  autonomous runner types persona/identity text into these
                  panes, so they need a running agent CLI to be useful.
  --hermes-roles  Roles passed through to the Hermes worker starter
                  (default: code,architect,frontend,backend,qa,research,memory).

Safety:
  - Does not store secrets.
  - Stores tmux pane ids in .ai-swarm/ai-swarm.env.
  - Refuses to replace an existing session unless --reset is supplied.
USAGE
}

reset_existing=false
with_hermes=false
hermes_roles=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --reset)
      reset_existing=true
      shift
      ;;
    --with-hermes)
      with_hermes=true
      shift
      ;;
    --hermes-roles)
      shift
      hermes_roles="${1:-}"
      shift || true
      ;;
    --hermes-roles=*)
      hermes_roles="${1#--hermes-roles=}"
      shift
      ;;
    --panes)
      shift
      PANE_COUNT="${1:-}"
      shift || true
      ;;
    --panes=*)
      PANE_COUNT="${1#--panes=}"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if ! [[ "$PANE_COUNT" =~ ^[0-9]+$ ]] || (( PANE_COUNT < 4 || PANE_COUNT > 10 )); then
  echo "--panes must be an integer from 4 to 10." >&2
  exit 2
fi

if ! command -v tmux >/dev/null 2>&1; then
  echo "tmux is not installed or not on PATH." >&2
  exit 127
fi

mkdir -p "$STATE_DIR"

if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
  if [[ "$reset_existing" != true ]]; then
    echo "tmux session '$SESSION_NAME' already exists. Re-run with --reset to recreate it." >&2
    exit 1
  fi
  # P0-2: kill-session만 하면 pane 안의 자식 프로세스가 orphan으로 남는다.
  # swarm-cleanup.sh가 각 pane 프로세스 트리를 회수한 뒤 세션을 종료한다.
  cleanup_script="$(dirname "$0")/swarm-cleanup.sh"
  if [[ -f "$cleanup_script" ]]; then
    AI_SWARM_SESSION="$SESSION_NAME" AI_SWARM_STATE_DIR="$STATE_DIR" bash "$cleanup_script" || true
  else
    tmux kill-session -t "$SESSION_NAME"
  fi
fi

# Force a large detached window so 10 panes fit even when this runs headless
# over SSH (default 80x24 has no room past ~4 splits → "no space for new pane").
discussion_pane="$(tmux new-session -d -s "$SESSION_NAME" -n "swarm" -x 320 -y 90 -c "$PWD" -P -F "#{pane_id}")"
tmux set-option -t "$SESSION_NAME" pane-border-status top >/dev/null
tmux set-option -t "$SESSION_NAME" pane-border-format "#{pane_index}: #{pane_title}" >/dev/null

tmux select-pane -t "$discussion_pane" -T "${titles[0]}"

pane_ids=(
  "$discussion_pane"
)

for ((i = 1; i < PANE_COUNT; i++)); do
  next_pane="$(tmux split-window -t "$SESSION_NAME:0" -c "$PWD" -P -F "#{pane_id}")"
  tmux select-pane -t "$next_pane" -T "${titles[$i]}"
  pane_ids+=("$next_pane")
  # Re-tile after every split so each pane keeps enough room for the next one.
  tmux select-layout -t "$SESSION_NAME" tiled >/dev/null
done

tmux select-layout -t "$SESSION_NAME" tiled >/dev/null

{
  echo "# Generated by scripts/setup-agent-swarm.sh"
  echo "AI_SWARM_SESSION=${SESSION_NAME}"
  echo "AI_SWARM_PANE_COUNT=${PANE_COUNT}"
  for i in "${!pane_ids[@]}"; do
    role_upper="$(printf '%s' "${roles[$i]}" | tr '[:lower:]' '[:upper:]')"
    echo "AI_SWARM_PANE_${role_upper}=${pane_ids[$i]}"
  done
} > "$ENV_FILE"

for i in "${!pane_ids[@]}"; do
  # P0-2: job control(monitor mode)을 켜면 pane shell이 실행하는 각 foreground
  # 명령이 자기 process group을 갖는다 → 정리/종료 시 그룹 단위로 시그널 전달이
  # 가능해지고, 자식이 부모와 함께 회수되기 쉬워진다.
  tmux send-keys -t "${pane_ids[$i]}" "set -m 2>/dev/null || true" C-m
  tmux send-keys -t "${pane_ids[$i]}" "printf '\\033]2;%s\\033\\\\' '${titles[$i]}'" C-m
  tmux send-keys -t "${pane_ids[$i]}" "echo '${titles[$i]} ready. Role: ${roles[$i]}.'" C-m
done

echo "Created tmux session '${SESSION_NAME}'."
echo "Pane ids saved to ${ENV_FILE}."
echo "Attach with: tmux attach -t ${SESSION_NAME}"

if [[ "$with_hermes" == true ]]; then
  hermes_starter="$(dirname "$0")/swarm-start-hermes-workers.sh"
  if [[ ! -f "$hermes_starter" ]]; then
    echo "Missing ${hermes_starter}; cannot start Hermes workers." >&2
    exit 1
  fi
  hermes_args=()
  if [[ -n "$hermes_roles" ]]; then
    hermes_args+=(--roles "$hermes_roles")
  fi
  AI_SWARM_SESSION="$SESSION_NAME" AI_SWARM_STATE_DIR="$STATE_DIR" \
    bash "$hermes_starter" "${hermes_args[@]}"
fi
