#!/usr/bin/env bash
set -euo pipefail

SESSION_NAME="${AI_SWARM_SESSION:-ai-swarm}"
STATE_DIR="${AI_SWARM_STATE_DIR:-.ai-swarm}"
ENV_FILE="${STATE_DIR}/${SESSION_NAME}.env"
PANE_COUNT="${AI_SWARM_PANE_COUNT:-10}"

roles=(
  discussion
  orchestrator
  status
  code
  architect
  frontend
  backend
  qa
  research
  memory
)

titles=(
  "Discussion & Planning"
  "Orchestrator Control"
  "Status & Monitor"
  "Agent - Code Expert"
  "Agent - Architect"
  "Agent - Frontend Dev"
  "Agent - Backend Dev"
  "Agent - QA & Security"
  "Agent - Research Scout"
  "Agent - Memory Curator"
)

usage() {
  cat <<'USAGE'
Usage:
  scripts/setup-agent-swarm.sh [--reset] [--panes 4-10]

Creates the ai-swarm tmux session with 4 to 10 role-based panes.

Options:
  --reset   Kill and recreate an existing ai-swarm session.
  --panes   Number of panes to create. Defaults to 10.

Safety:
  - Does not store secrets.
  - Stores tmux pane ids in .ai-swarm/ai-swarm.env.
  - Refuses to replace an existing session unless --reset is supplied.
USAGE
}

reset_existing=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --reset)
      reset_existing=true
      shift
      ;;
    --panes)
      shift
      PANE_COUNT="${1:-}"
      shift || true
      ;;
    --panes=*)
      PANE_COUNT="${1#--panes=}"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if ! [[ "$PANE_COUNT" =~ ^[0-9]+$ ]] || (( PANE_COUNT < 4 || PANE_COUNT > 10 )); then
  echo "--panes must be an integer from 4 to 10." >&2
  exit 2
fi

if ! command -v tmux >/dev/null 2>&1; then
  echo "tmux is not installed or not on PATH." >&2
  exit 127
fi

mkdir -p "$STATE_DIR"

if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
  if [[ "$reset_existing" != true ]]; then
    echo "tmux session '$SESSION_NAME' already exists. Re-run with --reset to recreate it." >&2
    exit 1
  fi
  tmux kill-session -t "$SESSION_NAME"
fi

discussion_pane="$(tmux new-session -d -s "$SESSION_NAME" -n "swarm" -c "$PWD" -P -F "#{pane_id}")"
tmux set-option -t "$SESSION_NAME" pane-border-status top >/dev/null
tmux set-option -t "$SESSION_NAME" pane-border-format "#{pane_index}: #{pane_title}" >/dev/null

tmux select-pane -t "$discussion_pane" -T "${titles[0]}"

pane_ids=(
  "$discussion_pane"
)

for ((i = 1; i < PANE_COUNT; i++)); do
  next_pane="$(tmux split-window -t "$SESSION_NAME:0" -c "$PWD" -P -F "#{pane_id}")"
  tmux select-pane -t "$next_pane" -T "${titles[$i]}"
  pane_ids+=("$next_pane")
done

tmux select-layout -t "$SESSION_NAME" tiled >/dev/null

{
  echo "# Generated by scripts/setup-agent-swarm.sh"
  echo "AI_SWARM_SESSION=${SESSION_NAME}"
  echo "AI_SWARM_PANE_COUNT=${PANE_COUNT}"
  for i in "${!pane_ids[@]}"; do
    role_upper="$(printf '%s' "${roles[$i]}" | tr '[:lower:]' '[:upper:]')"
    echo "AI_SWARM_PANE_${role_upper}=${pane_ids[$i]}"
  done
} > "$ENV_FILE"

for i in "${!pane_ids[@]}"; do
  tmux send-keys -t "${pane_ids[$i]}" "printf '\\033]2;%s\\033\\\\' '${titles[$i]}'" C-m
  tmux send-keys -t "${pane_ids[$i]}" "echo '${titles[$i]} ready. Role: ${roles[$i]}.'" C-m
done

echo "Created tmux session '${SESSION_NAME}'."
echo "Pane ids saved to ${ENV_FILE}."
echo "Attach with: tmux attach -t ${SESSION_NAME}"
