#!/usr/bin/env bash
set -euo pipefail

SESSION_NAME="${AI_SWARM_SESSION:-ai-swarm}"
STATE_DIR="${AI_SWARM_STATE_DIR:-.ai-swarm}"
ENV_FILE="${STATE_DIR}/${SESSION_NAME}.env"

roles=(
  discussion
  orchestrator
  status
  code
  architect
  frontend
  backend
  qa
)

titles=(
  "Discussion & Planning"
  "Orchestrator Control"
  "Status & Monitor"
  "Agent - Code Expert"
  "Agent - Architect"
  "Agent - Frontend Dev"
  "Agent - Backend Dev"
  "Agent - QA & Security"
)

usage() {
  cat <<'USAGE'
Usage:
  scripts/setup-agent-swarm.sh [--reset]

Creates the ai-swarm tmux session with 8 role-based panes.

Options:
  --reset   Kill and recreate an existing ai-swarm session.

Safety:
  - Does not store secrets.
  - Stores tmux pane ids in .ai-swarm/ai-swarm.env.
  - Refuses to replace an existing session unless --reset is supplied.
USAGE
}

reset_existing=false
for arg in "$@"; do
  case "$arg" in
    --reset)
      reset_existing=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if ! command -v tmux >/dev/null 2>&1; then
  echo "tmux is not installed or not on PATH." >&2
  exit 127
fi

mkdir -p "$STATE_DIR"

if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
  if [[ "$reset_existing" != true ]]; then
    echo "tmux session '$SESSION_NAME' already exists. Re-run with --reset to recreate it." >&2
    exit 1
  fi
  tmux kill-session -t "$SESSION_NAME"
fi

discussion_pane="$(tmux new-session -d -s "$SESSION_NAME" -n "swarm" -c "$PWD" -P -F "#{pane_id}")"
tmux set-option -t "$SESSION_NAME" pane-border-status top >/dev/null
tmux set-option -t "$SESSION_NAME" pane-border-format "#{pane_index}: #{pane_title}" >/dev/null

tmux select-pane -t "$discussion_pane" -T "${titles[0]}"

right_root="$(tmux split-window -h -t "$discussion_pane" -p 65 -c "$PWD" -P -F "#{pane_id}")"
tmux select-pane -t "$right_root" -T "${titles[3]}"

orchestrator_pane="$(tmux split-window -v -t "$discussion_pane" -p 66 -c "$PWD" -P -F "#{pane_id}")"
tmux select-pane -t "$orchestrator_pane" -T "${titles[1]}"

status_pane="$(tmux split-window -v -t "$orchestrator_pane" -p 50 -c "$PWD" -P -F "#{pane_id}")"
tmux select-pane -t "$status_pane" -T "${titles[2]}"

code_pane="$right_root"
tmux select-pane -t "$code_pane" -T "${titles[3]}"
architect_pane="$(tmux split-window -v -t "$code_pane" -p 83 -c "$PWD" -P -F "#{pane_id}")"
tmux select-pane -t "$architect_pane" -T "${titles[4]}"
frontend_pane="$(tmux split-window -v -t "$architect_pane" -p 80 -c "$PWD" -P -F "#{pane_id}")"
tmux select-pane -t "$frontend_pane" -T "${titles[5]}"
backend_pane="$(tmux split-window -v -t "$frontend_pane" -p 75 -c "$PWD" -P -F "#{pane_id}")"
tmux select-pane -t "$backend_pane" -T "${titles[6]}"
qa_pane="$(tmux split-window -v -t "$backend_pane" -p 67 -c "$PWD" -P -F "#{pane_id}")"
tmux select-pane -t "$qa_pane" -T "${titles[7]}"

pane_ids=(
  "$discussion_pane"
  "$orchestrator_pane"
  "$status_pane"
  "$code_pane"
  "$architect_pane"
  "$frontend_pane"
  "$backend_pane"
  "$qa_pane"
)

{
  echo "# Generated by scripts/setup-agent-swarm.sh"
  echo "AI_SWARM_SESSION=${SESSION_NAME}"
  for i in "${!roles[@]}"; do
    role_upper="$(printf '%s' "${roles[$i]}" | tr '[:lower:]' '[:upper:]')"
    echo "AI_SWARM_PANE_${role_upper}=${pane_ids[$i]}"
  done
} > "$ENV_FILE"

for i in "${!roles[@]}"; do
  tmux send-keys -t "${pane_ids[$i]}" "printf '\\033]2;%s\\033\\\\' '${titles[$i]}'" C-m
  tmux send-keys -t "${pane_ids[$i]}" "echo '${titles[$i]} ready. Role: ${roles[$i]}.'" C-m
done

echo "Created tmux session '${SESSION_NAME}'."
echo "Pane ids saved to ${ENV_FILE}."
echo "Attach with: tmux attach -t ${SESSION_NAME}"
