#!/usr/bin/env bash

swarm_lock_path=""

swarm_fail() {
  echo "$*" >&2
  exit 1
}

acquire_lock() {
  local lock_root="${STATE_DIR}/locks"
  local timeout="${AI_SWARM_LOCK_TIMEOUT:-30}"
  local waited=0
  mkdir -p "$lock_root"
  swarm_lock_path="${lock_root}/swarm.lock"
  while ! mkdir "$swarm_lock_path" 2>/dev/null; do
    if (( waited >= timeout )); then
      swarm_fail "Timed out acquiring swarm lock: ${swarm_lock_path}"
    fi
    sleep 1
    waited=$((waited + 1))
  done
  printf '%s\n' "$$" > "${swarm_lock_path}/pid"
  trap release_lock EXIT
  trap 'release_lock; exit 130' INT TERM
}

release_lock() {
  if [[ -n "${swarm_lock_path:-}" && -d "$swarm_lock_path" ]]; then
    rm -rf "$swarm_lock_path"
  fi
}

load_swarm_env() {
  local requested_session="$SESSION_NAME"
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "Missing swarm env file: $ENV_FILE" >&2
    echo "Run scripts/setup-agent-swarm.sh first." >&2
    exit 1
  fi
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  local env_session="${AI_SWARM_SESSION:-}"
  if [[ "$env_session" != "$requested_session" ]]; then
    swarm_fail "Swarm env session mismatch: expected '${requested_session}', found '${env_session:-unset}' in ${ENV_FILE}."
  fi
  SESSION_NAME="$requested_session"
}

require_tmux() {
  if ! command -v tmux >/dev/null 2>&1; then
    echo "tmux is not installed or not on PATH." >&2
    exit 127
  fi
}

require_live_session() {
  if ! tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
    swarm_fail "tmux session '${SESSION_NAME}' is not running."
  fi
}

require_live_pane() {
  local role="$1"
  local pane_id="$2"
  if [[ -z "$pane_id" ]]; then
    echo "Unknown role or missing pane id: $role" >&2
    usage >&2
    exit 2
  fi
  local actual_pane=""
  local actual_session=""
  if ! actual_pane="$(tmux display-message -p -t "$pane_id" "#{pane_id}" 2>/dev/null)"; then
    swarm_fail "stale pane id for role '${role}': ${pane_id}"
  fi
  if [[ "$actual_pane" != "$pane_id" ]]; then
    swarm_fail "stale pane id for role '${role}': expected ${pane_id}, found ${actual_pane}"
  fi
  if ! actual_session="$(tmux display-message -p -t "$pane_id" "#{session_name}" 2>/dev/null)"; then
    swarm_fail "stale pane id for role '${role}': ${pane_id}"
  fi
  if [[ "$actual_session" != "$SESSION_NAME" ]]; then
    swarm_fail "stale pane id for role '${role}': ${pane_id} belongs to session '${actual_session}', expected '${SESSION_NAME}'"
  fi
}

make_marker() {
  local role="$1"
  local now
  local random
  now="$(date -u +"%Y%m%dT%H%M%SZ")"
  if command -v od >/dev/null 2>&1; then
    random="$(od -An -N4 -tx1 /dev/urandom 2>/dev/null | tr -d ' \n')"
  else
    random="${RANDOM:-0}${RANDOM:-0}"
  fi
  printf 'AI_SWARM_MARKER:%s:%s:%s:%s:%s\n' "$SESSION_NAME" "$role" "$now" "$$" "${random:-0000}"
}

write_marker_metadata() {
  local role="$1"
  local pane_id="$2"
  local marker="$3"
  local file="${STATE_DIR}/last-marker-${role}.env"
  local tmp="${file}.$$"
  {
    echo "# Generated by scripts/swarm-send.sh"
    echo "AI_SWARM_LAST_MARKER=${marker}"
    echo "AI_SWARM_LAST_MARKER_SESSION=${SESSION_NAME}"
    echo "AI_SWARM_LAST_MARKER_ROLE=${role}"
    echo "AI_SWARM_LAST_MARKER_PANE=${pane_id}"
    echo "AI_SWARM_LAST_MARKER_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  } > "$tmp"
  mv "$tmp" "$file"
}

redact_swarm_output() {
  sed -E \
    -e 's/sk-[A-Za-z0-9_-]{8,}/[REDACTED:api_key]/g' \
    -e 's/Bearer[[:space:]]+[A-Za-z0-9._~+\/=-]+/[REDACTED:bearer_token]/g' \
    -e 's/(ANTHROPIC_AUTH_TOKEN|OPENAI_API_KEY|AUTH_TOKEN|API_KEY|SECRET|TOKEN)=([^[:space:]]+)/\1=[REDACTED:secret]/g' \
    -e 's/-----BEGIN [A-Z ]*PRIVATE KEY-----/[REDACTED:private_key]/g'
}
