#!/usr/bin/env bash
set -euo pipefail

SESSION_NAME="${AI_SWARM_SESSION:-ai-swarm}"
STATE_DIR="${AI_SWARM_STATE_DIR:-.ai-swarm}"
ENV_FILE="${STATE_DIR}/${SESSION_NAME}.env"
WORKER_STATE_FILE="${STATE_DIR}/${SESSION_NAME}.claude-workers.env"
CLAUDE_BIN="${CLAUDE_BIN_PATH:-claude}"
PERMISSION_MODE="${CLAUDE_WORKER_PERMISSION_MODE:-plan}"
MODEL="${CLAUDE_WORKER_MODEL:-sonnet}"
NAME_PREFIX="${CLAUDE_WORKER_NAME_PREFIX:-ai-swarm}"
DEFAULT_ROLES="code,architect,frontend,backend,qa,research,memory"

usage() {
  cat <<'USAGE'
Usage:
  scripts/swarm-start-claude-workers.sh [--roles role,role] [--model MODEL] [--permission-mode MODE]

Starts persistent interactive Claude Code sessions inside existing ai-swarm tmux panes.
This does not use `claude -p` or any headless Agent SDK path.

Defaults:
  roles: code,architect,frontend,backend,qa,research,memory
  model: sonnet
  permission mode: plan

Examples:
  scripts/setup-agent-swarm.sh --reset
  scripts/swarm-start-claude-workers.sh
  scripts/swarm-start-claude-workers.sh --roles code,qa --permission-mode plan

Safety:
  - Requires an existing tmux swarm env file.
  - Starts Claude in interactive mode only.
  - Default permission mode is plan, so workers inspect/plan before edits.
  - Does not send task prompts; use scripts/swarm-claude-task.sh for that.
USAGE
}

roles_csv="$DEFAULT_ROLES"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --roles)
      shift
      roles_csv="${1:-}"
      shift || true
      ;;
    --roles=*)
      roles_csv="${1#--roles=}"
      shift
      ;;
    --model)
      shift
      MODEL="${1:-}"
      shift || true
      ;;
    --model=*)
      MODEL="${1#--model=}"
      shift
      ;;
    --permission-mode)
      shift
      PERMISSION_MODE="${1:-}"
      shift || true
      ;;
    --permission-mode=*)
      PERMISSION_MODE="${1#--permission-mode=}"
      shift
      ;;
    --claude-bin)
      shift
      CLAUDE_BIN="${1:-}"
      shift || true
      ;;
    --claude-bin=*)
      CLAUDE_BIN="${1#--claude-bin=}"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$roles_csv" ]]; then
  echo "--roles must not be empty." >&2
  exit 2
fi

if ! command -v tmux >/dev/null 2>&1; then
  echo "tmux is not installed or not on PATH." >&2
  exit 127
fi

if ! command -v "$CLAUDE_BIN" >/dev/null 2>&1; then
  echo "Claude CLI not found: $CLAUDE_BIN" >&2
  exit 127
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing swarm env file: $ENV_FILE" >&2
  echo "Run scripts/setup-agent-swarm.sh first." >&2
  exit 1
fi

if ! tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
  echo "tmux session '$SESSION_NAME' is not running." >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

mkdir -p "$STATE_DIR"
{
  echo "# Generated by scripts/swarm-start-claude-workers.sh"
  echo "AI_SWARM_SESSION=${SESSION_NAME}"
  echo "CLAUDE_WORKER_PERMISSION_MODE=${PERMISSION_MODE}"
  echo "CLAUDE_WORKER_MODEL=${MODEL}"
  echo "CLAUDE_WORKER_STARTED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$WORKER_STATE_FILE"

IFS=',' read -r -a roles <<< "$roles_csv"
for role in "${roles[@]}"; do
  role="$(printf '%s' "$role" | xargs)"
  if [[ -z "$role" ]]; then
    continue
  fi

  role_key="$(printf '%s' "$role" | tr '[:lower:]' '[:upper:]')"
  pane_var="AI_SWARM_PANE_${role_key}"
  pane_id="${!pane_var:-}"

  if [[ -z "$pane_id" ]]; then
    echo "Unknown role or missing pane id: $role" >&2
    exit 2
  fi

  session_name="${NAME_PREFIX}-${role}"
  command_line="${CLAUDE_BIN} --name ${session_name} --permission-mode ${PERMISSION_MODE}"
  if [[ -n "$MODEL" ]]; then
    command_line="${command_line} --model ${MODEL}"
  fi

  tmux send-keys -t "$pane_id" -l "$command_line"
  tmux send-keys -t "$pane_id" C-m
  echo "CLAUDE_WORKER_${role_key}_PANE=${pane_id}" >> "$WORKER_STATE_FILE"
  echo "CLAUDE_WORKER_${role_key}_NAME=${session_name}" >> "$WORKER_STATE_FILE"
  echo "Started Claude worker for ${role} (${pane_id}) as ${session_name}."
done

echo "Claude worker state saved to ${WORKER_STATE_FILE}."
