import type {
  MemoryAdapter,
    MemoryAdapterContext,
      MemoryRecord,
        MemoryRecallResult,
          MemoryContextPacket,
            MemoryStats,
              MemoryRelation,
              } from "./adapter.js";
              import { MemoryAdapterError } from "./errors.js";

              // ---------------------------------------------------------------------------
              // Utilities
              // ---------------------------------------------------------------------------

              function tokenize(text: string): string[] {
                return text.toLowerCase().split(/\s+/).filter(Boolean);
                }

                function stableId(input: string, salt: string): string {
                  let h = 0;
                    const s = input + salt;
                      for (let i = 0; i < s.length; i++) {
                          h = (Math.imul(31, h) + s.charCodeAt(i)) | 0;
                            }
                              return `lh_${(h >>> 0).toString(16).padStart(8, "0")}`;
                              }

                              function scoreRecord(record: MemoryRecord, queryTokens: string[], now: number): number {
                                const contentTokens = new Set(tokenize(record.content));
                                  const overlap = queryTokens.filter((t) => contentTokens.has(t)).length;
                                    const tokenScore = queryTokens.length > 0 ? overlap / queryTokens.length : 0;
                                      // Recency bonus: decay over 7 days, max +0.3
                                        const ageMs = now - (record.createdAt ?? now);
                                          const recencyBonus = Math.max(0, 0.3 * (1 - ageMs / (7 * 24 * 60 * 60 * 1000)));
                                            const pinBonus = record.activation === "pinned" ? 0.4 : 0;
                                              return tokenScore + recencyBonus + pinBonus;
                                              }

                                              // ---------------------------------------------------------------------------
                                              // LocalHeuristicAdapter
                                              // ---------------------------------------------------------------------------
                                              // In-memory adapter for local / offline use. Scores records by token overlap +
                                              // recency + pin status. Suitable for MacBook offline fallback and unit tests
                                              // that need a lightweight but non-trivial scorer.

                                              export class LocalHeuristicAdapter implements MemoryAdapter {
                                                readonly kind = "local_heuristic" as const;
                                                  readonly profileId: string;

                                                    private records = new Map<string, MemoryRecord>();
                                                      private relations: MemoryRelation[] = [];
                                                        private _seq = 0;

                                                          constructo
                                                              this.profileId = profileId;
                                                                }

                                                                  async recall(
                                                                      query: string,
                                                                          opts: { topK?: number; includeUntrusted?: boolean; minScore?: number } = {},
                                                                              ctx: MemoryAdapterContext,
                                                                                ): Promise<MemoryRecallResult[]> {
                                                                                    const { topK = 5, includeUntrusted = false, minScore = 0.05 } = opts;
                                                                                        const queryTokens = tokenize(query);
                                                                                            const now = Date.now();

                                                                                                const candidates = Array.from(this.records.values()).filter((r) => {
                                                                                                      if (r.activation === "forgotten") return false;
                                                                                                            if (!includeUntrusted && r.trustLevel === "untrusted") return false;
                                                                                                                  return true;
                                                                                                                      });
                                                                                                                      
                                                                                                                          return candidates
                                                                                                                                .map((r) => ({ record: r, score: scoreRecord(r, queryTokens, now) }))
                                                                                                                                      .filter(({ score }) => score >= minScore)
                                                                                                                                            .sort((a, b) => b.score - a.score)
                                                                                                                                                  .slice(0, topK)
                                                                                                                                                        .map(({ record, score }) => ({ record, score }));
                                                                                                                                                          }
                                                                                                                                                          
                                                                                                                                                            async remember(
                                                                                                                                                                content: string,
                                                                                                                                                                    meta: Partial<Pick<MemoryRecord, "layer" | "trustLevel" | "tags">>,
                                                                                                                                                                        ctx: MemoryAdapterContext,
                                                                                                                                                                          ): Promise<MemoryRecord> {
                                                                                                                                                                              if (ctx.trustLevel === "untrusted" && meta.layer === "long_term") {
                                                                                                                                                                                    throw new MemoryAdapterError("trust_violation", {});
                                                                                                                                                                                        }
                                                                                                                                                                                        
                                                                                                                                                                                            const id = stableId(content, String(this._seq++));
                                                                                                                                                                                                const record: MemoryRecord = {
                                                                                                                                                                                                      id,
                                                                                                                                                                                                            content,
                                                                                                                                                                                                                  layer: meta.layer ?? "session",
                                                                                                                                                                                                                        trustLevel: meta.trustLevel ?? ctx.trustLevel ?? "trusted",
                                                                                                                                                                                                                              tags: meta.tags ?? [],
                                                                                                                                                                                                                                    activation: "suggested",
                                                                                                                                                                                                                                          createdAt: Date.now(),
                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                  this.records.set(id, record);
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                      ctx.onEvent?.({
                                                                                                                                                                                                                                                            type: "memory.archival_write.requested",
                                                                                                                                                                                                                                                                  recordId: id,
                                                                                                                                                                                                                                                                        adapterId: this.profileId,
                                                                                                                                                                                                                                                                            } as any);
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                return record;
                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                    async memoryContext(
                                                                                                                                                                                                                                                                                        query: string,
                                                                                                                                                                                                                                                                                            opts: { topK?: number } = {},
                                                                                                                                                                                                                                                                                                ctx: MemoryAdapterContext,
                                                                                                                                                                                                                                                                                                  ): Promise<MemoryContextPacket> {
                                                                                                                                                                                                                                                                                                      const results = await this.recall(query, opts, ctx);
                                                                                                                                                                                                                                                                                                          return {
                                                                                                                                                                                                                                                                                                                query,
                                                                                                                                                                                                                                                                                                                      records: results.map((r) => r.record),
                                                                                                                                                                                                                                                                                                                            scores: results.map((r) => r.score),
                                                                                                                                                                                                                                                                                                                                  adapterId: this.profileId,
                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                          async pin(recordId: string, ctx: MemoryAdapterContext): Promise<void> {
                                                                                                                                                                                                                                                                                                                                              const r = this.records.get(recordId);
                                                                                                                                                                                                                                                                                                                                                  if (!r) throw new MemoryAdapterError("not_found", { recordId });
                                                                                                                                                                                                                                                                                                                                                      this.records.set(recordId, { ...r, activation: "pinned" });
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                          async forget(recordId: string, ctx: MemoryAdapterContext): Promise<void> {
                                                                                                                                                                                                                                                                                                                                                              const r = this.records.get(recordId);
                                                                                                                                                                                                                                                                                                                                                                  if (!r) throw new MemoryAdapterError("not_found", { recordId });
                                                                                                                                                                                                                                                                                                                                                                      this.records.set(recordId, { ...r, activation: "forgotten" });
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                          async activateMemories(
                                                                                                                                                                                                                                                                                                                                                                              recordIds: string[],
                                                                                                                                                                                                                                                                                                                                                                                  ctx: MemoryAdapterContext,
                                                                                                                                                                                                                                                                                                                                                                                    ): Promise<void> {
                                                                                                                                                                                                                                                                                                                                                                                        for (const id of recordIds) {
                                                                                                                                                                                                                                                                                                                                                                                              const r = this.records.get(id);
                                                                                                                                                                                                                                                                                                                                                                                                    if (r && r.activation !== "forgotten") {
                                                                                                                                                                                                                                                                                                                                                                                                            this.records.set(id, { ...r, activation: "active" });
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                          async createRelations(
                                                                                                                                                                                                                                                                                                                                                                                                                              relations: MemoryRelation[],
                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx: MemoryAdapterContext,
                                                                                                                                                                                                                                                                                                                                                                                                                                    ): Promise<void> {
                                                                                                                                                                                                                                                                                                                                                                                                                                        this.relations.push(...relations);
                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                            async stats(ctx: MemoryAdapterContext): Promise<MemoryStats> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                const all = Array.from(this.records.values());
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          total: all.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                active: all.filter((r) => r.activation === "active").length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pinned: all.filter((r) => r.activation === "pinned").length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            forgotten: all.filter((r) => r.activation === "forgotten").length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  suggested: all.filter((r) => r.activation === "suggested").length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
