import rawData from "./debateMockData.json";

/**
 * 50 debate-scenario mock dataset generated by 니뭉 (Manus AI) on
 * 2026-05-26. Used for desktop UI mock screens (Conversation / Debate /
 * Tmux Swarm), demo videos, and as a deterministic test fixture.
 *
 * Source: docs/manus/debate-mock-data-output.yaml
 * Input prompt: docs/manus/debate-mock-data-input.md
 *
 * 17 personas, 8 categories, 5 utterance tags, 258 total utterances.
 *
 * Safety contract — verified at import time:
 *   - All scenarios are pseudonymized under "REFLECORE" — no real company
 *     names, user identities, or secrets bleed into the fixture.
 *   - Persona speakers map 1:1 to dirs under `agents/<dir>/` (including
 *     `yohane` and `risk_officer`).
 *   - Tag enum is closed: each utterance carries exactly one of five tags
 *     matching the debate engine's `DebateTag` (see packages/protocol).
 *
 * This file deliberately re-declares the mock-side types instead of
 * importing the protocol enums. The fixture is for UI seeding, not
 * runtime debate execution — keeping it self-contained means edits to
 * the protocol schema do not silently break mock data quality.
 */

/** 8 scenario categories (Manus prompt distribution: 10/10/10/5/5/5/3/2). */
export type DebateMockCategory =
  | "product"
  | "b2b"
  | "code"
  | "risk"
  | "operations"
  | "meta"
  | "companion_delegation"
  | "daily";

/** 5 utterance tags — matches `debateTagSchema` in @ai-orchestrator/protocol. */
export type DebateMockTag =
  | "agreement"
  | "objection"
  | "evidence"
  | "risk"
  | "coding_impact";

/** Speaker = persona directory name under `agents/`. 17 distinct values. */
export type DebateMockSpeaker =
  | "orchestrator"
  | "architect"
  | "builder"
  | "reviewer"
  | "skeptic"
  | "verifier"
  | "memory_curator"
  | "executor"
  | "external"
  | "auditor"
  | "researcher"
  | "negotiator"
  | "risk_officer"
  | "mediator"
  | "watchdog"
  | "domain_expert"
  | "yohane";

export type DebateMockUtterance = {
  /** 1-indexed round number within the scenario (1..7). */
  round: number;
  speaker: DebateMockSpeaker;
  tag: DebateMockTag;
  text: string;
};

export type DebateMockScenario = {
  /** Stable id like "debate_001" — safe as a React key. */
  id: string;
  category: DebateMockCategory;
  /** Short topic line, often a decision or a defect. */
  topic: string;
  /** Background paragraph the model would have been primed with. */
  context: string;
  /** Persona dirs invited to this debate (3~6 entries). */
  participants: DebateMockSpeaker[];
  /** Utterances in order of round + speaker turn. */
  rounds: DebateMockUtterance[];
  /** Curator-supplied wrap-up the final round should resolve toward. */
  expectedResolution: string;
};

export type DebateMockDataset = {
  dataset: string;
  version: string;
  language: string;
  projectAlias: string;
  safetyRules: readonly string[];
  categoryDistribution: Readonly<Record<DebateMockCategory, number>>;
  /** One-line voice cheat sheet per persona. */
  personaVoiceCheatSheet: Readonly<Record<DebateMockSpeaker, string>>;
  scenarios: readonly DebateMockScenario[];
};

/*
 * The raw JSON was emitted by `pnpm dlx js-yaml` from the YAML source.
 * YAML conventionally uses snake_case for keys; we wrap it once at the
 * module boundary so the rest of the desktop code sees a TypeScript-
 * conventional camelCase shape. This single mapping point also lets us
 * stably type-narrow the JSON `unknown` into the closed enums above.
 */
type RawScenario = {
  id: string;
  category: DebateMockCategory;
  topic: string;
  context: string;
  participants: DebateMockSpeaker[];
  rounds: DebateMockUtterance[];
  expected_resolution: string;
};

type RawDataset = {
  dataset: string;
  version: string;
  language: string;
  project_alias: string;
  safety_rules: string[];
  category_distribution: Record<DebateMockCategory, number>;
  persona_voice_cheat_sheet: Record<DebateMockSpeaker, string>;
  scenarios: RawScenario[];
};

const raw = rawData as unknown as RawDataset;

export const debateMockDataset: DebateMockDataset = {
  dataset: raw.dataset,
  version: raw.version,
  language: raw.language,
  projectAlias: raw.project_alias,
  safetyRules: raw.safety_rules,
  categoryDistribution: raw.category_distribution,
  personaVoiceCheatSheet: raw.persona_voice_cheat_sheet,
  scenarios: raw.scenarios.map((s): DebateMockScenario => ({
    id: s.id,
    category: s.category,
    topic: s.topic,
    context: s.context,
    participants: s.participants,
    rounds: s.rounds,
    expectedResolution: s.expected_resolution,
  })),
};

/** All 50 scenarios. */
export const debateMockScenarios = debateMockDataset.scenarios;

/**
 * Subset helper. Pass one or more categories; returns scenarios in their
 * declared order. Useful for demo screens that want a focused slice
 * (e.g. only `companion_delegation` to showcase 채아린's delegate flow).
 */
export function debateMockScenariosByCategory(
  ...categories: DebateMockCategory[]
): readonly DebateMockScenario[] {
  if (categories.length === 0) return debateMockScenarios;
  const wanted = new Set(categories);
  return debateMockScenarios.filter((s) => wanted.has(s.category));
}

/**
 * Lookup by id. Returns `undefined` for unknown ids — call sites that
 * key off a route param should guard for this rather than throw.
 */
export function findDebateMockScenario(id: string): DebateMockScenario | undefined {
  return debateMockScenarios.find((s) => s.id === id);
}

/** Total utterance count across all scenarios — useful for fixture stats. */
export const debateMockTotalUtterances = debateMockScenarios.reduce(
  (sum, s) => sum + s.rounds.length,
  0,
);
